baseURL = "https://austingayler.github.io/blog/"
languageCode = "en-us"
title = "AJ's Blog"
theme = "PaperMod"
contentDir = "../content"
[pagination]
  pagerSize = 10

[params]
  author = "AJ"
  description = "Musings, beta, whatever"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[params.homeInfoParams]
  Title = "AJ's Blog"
  Content = "Musings, beta, whatever."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/austingayler"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]
